core/urls.py
from django.contrib import admin
from django.urls import path, include
from contest.views.standard_views import (
    CommonIndexView,
    PanelIndexView,
    AuthorIndexView,
    AuthorUpdateView,
    AuthorDeleteView,
    AuthorCreateView,
    SongIndexView,
    SongCreateView,
    SongUpdateView,
    SongDeleteView,
    LoginView,
    logout_view,
    VoteView,
    ContestSubmissionView
)

from contest.views.generic_views import (
    AlbumIndexView,
    AlbumCreateView,
    AlbumUpdateView,
    AlbumDeleteView
)
# te adresy URL są zrobione za pomocą
album_patterns = ([
    # http://127.0.0.1:8000/panel/albums/
    path('', AlbumIndexView.as_view(), name='index'),
    path('create/', AlbumCreateView.as_view(), name='create'),
    path('<int:pk>/edit/', AlbumUpdateView.as_view(), name="edit"),
    path('<int:pk>/delete/', AlbumDeleteView.as_view(), name="delete"),

    # http://127.0.0.1:8000/panel/albums/album_id/songs/
    path('<int:album_id>/songs/', SongIndexView.as_view(), name='songs-index'),

    path('<int:album_id>/songs/create', SongCreateView.as_view(), name='songs-create'),
    # http://127.0.0.1:8000/panel/albums/album_id/songs/song_id/edit

    path('<int:album_id>/songs/<int:song_id>/edit', SongUpdateView.as_view(), name='songs-edit'),

    path('<int:album_id>/songs/<int:song_id>/delete', SongDeleteView.as_view(), name='songs-delete'),
], 'albums')

author_patterns = ([

    path('', AuthorIndexView.as_view(), name='index'),
    path('create/', AuthorCreateView.as_view(), name='create'),
    path('<int:id>/edit/', AuthorUpdateView.as_view(), name='update'),
    path('<int:id>/delete/', AuthorDeleteView.as_view(), name='delete'),
], 'authors')

panel_patterns = ([
    # główna strona dla ZALOGOWANYCH, url: http://127.0.0.1:8000/panel/
    path('', PanelIndexView.as_view(), name='index'),

    # http://127.0.0.1:8000/panel/authors/
    path('authors/', include(author_patterns)),  # zawiera ścieżki z author_patterns

    #  http://127.0.0.1:8000/panel/albums/
    path('albums/', include(album_patterns)),  # zawiera ścieżki z album_patterns
], 'panel')

urlpatterns = [
    path('admin/', admin.site.urls),

    # główna strona palikacji dla nie zalogowanych, url: http://127.0.0.1:8000
    path('', CommonIndexView.as_view(), name='common-index'),

    # główna strona dla ZALOGOWANYCH, url: http://127.0.0.1:8000/panel/
    path('panel/', include(panel_patterns)),  # zawiera ścieżki z panel_patterns

    #
    path('login/', LoginView.as_view(), name='login'),

    #
    path('logout/', logout_view, name='logout'),

    # głosowanie na piosenki, widok bez szablonu html
    path('vote/', VoteView.as_view(), name='vote'),

    # zliczanie głosów, widok bez szablonu html
    path('submission/', ContestSubmissionView.as_view(), name='submission')
]

contest/models.py
from django.core.exceptions import ValidationError
from django.db import models
from datetime import datetime


class Author(models.Model):
    first_name = models.CharField(max_length=64, null=True)
    last_name = models.CharField(max_length=64, null=True)
    birth_date = models.DateField(null=True)
    band_name = models.CharField(max_length=255)
    debut = models.DateField(null=True, verbose_name="rok debiutu")

    @property
    def name(self):
        if (self.first_name is not None) and (self.last_name is not None):
            return "{} {}".format(self.first_name, self.last_name)
        return self.band_name

    def __str__(self):
        return self.band_name

class Album(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name="Nazwa zespołu", related_name="author")
    album_name = models.CharField(max_length=100, verbose_name="Nazwa albumu")
    # poniżej ustawiamy jakie informacje będzie zwracać klasa
    # ponieważ "author" ma klucz obcy do Author to "Album" może zwracać dane z klasy Author
    def __str__(self):
        return f"{self.album_name} ({self.author.band_name})"


class Song(models.Model):
    song_name = models.CharField(max_length=64)
    year = models.IntegerField(verbose_name="Rok powstania piosenki")
    album = models.ForeignKey(Album, on_delete=models.CASCADE, related_name="album")
    yt_link = models.CharField(max_length=255, null=True, )
    sort_order = models.IntegerField(default=0)

    # walidator dla pola "year" i "yt_link"
    def clean(self):
        if int(self.year) < 1900 or int(self.year) > datetime.now().year:
            raise ValidationError('Year is not valid, it should be between 1900 - curren year')
        if self.yt_link != '#' and not self.yt_link.startswith('https://www.youtube.com'):
            raise ValidationError('Wrong youtube link!')

    def __str__(self):
        return "{} ({})".format(self.song_name, self.album.album_name)


class SongVotes(models.Model):
    song = models.ForeignKey(Song, on_delete=models.CASCADE, related_name="songVotes")
    vote_hash = models.TextField()

    def __str__(self):
        return self.vote_hash


class ContestSubmission(models.Model):
    song = models.ForeignKey(Song, on_delete=models.CASCADE, related_name="songSubmission")
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    telephone = models.CharField(max_length=15)
    email = models.CharField(max_length=64)
    context = models.TextField()

    def __str__(self):
        return "{} {} ({})".format(self.first_name, self.last_name, self.song.song_name)

templates/contest/panel/album/create.html
{% extends 'panel.html' %}

{#formatuje formularze do szerokości strony, trzeba go dodać w setin.py CRISPY_TEMPLATE_PACK = 'bootstrap4'#}
{% load crispy_forms_tags %}
​
{% block title %}Dodaj album{% endblock %}
​
{% block content %}
    <div class="jumbotron py-2 px-4">
        <h1 class="display-4">Dodaj album</h1>
        <hr class="my-4">
        <a class="btn btn-info" href="{%  url 'panel:albums:index' %}" role="button">Wróć do spisu</a>
    </div>
    <div>
        <form method="post" action="{% url 'panel:albums:create' %}" class="form">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Zapisz dane</button>
        </form>
    </div>
{% endblock %}

templates/contest/panel/album/delete.html
{% extends 'panel.html' %}
​
{% block title %}Usuń album{% endblock %}
{% block content %}
<div class="jumbotron py-2 px-4">
    <h1 class="display-4">Usuń album</h1>
    <hr class="my-4">
    <a class="btn btn-info" href="{% url 'panel:albums:index' %}" role="button">Wróć do spisu</a>
</div>
<div>
{#generyki wymagają pk od wesjic 3 Django#}
{#generyki wymagają pk od wesjic 3 Django#}
    <form method="POST" action="{% url 'panel:albums:delete' pk=object.id %}" class="form">
        {% csrf_token %}
        Czy na pewno chcesz usunąć {{ object }}?
    <button type="submit" class="btn btn-danger">Usuń</button>
    </form>
</div>
{% endblock %}

templates/contest/panel/album/edit.html
{% extends 'panel.html' %}

{#formatuje formularze do szerokości strony, trzeba go dodać w settings.py#}
{#CRISPY_TEMPLATE_PACK = 'bootstrap4'#}
{% load crispy_forms_tags %}
​
{% block title %}Edytuj albumy{% endblock %}
{% block content %}
<div class="jumbotron py-2 px-4">
    <h1 class="display-4">Edytuj album</h1>
    <hr class="my-4">
    <a class="btn btn-info" href="{% url 'panel:albums:index' %}" role="button">Wróć do listy albumów</a>
</div>
<div>
{#generyki wymagają pk od wesjic 3 Django#}
{#generyki wymagają pk od wesjic 3 Django#}
    <form method="POST" action="{% url 'panel:albums:edit' pk=object.id %}" class="form">
        {% csrf_token %}
        {{ form|crispy }}
    <button type="submit" class="btn btn-success">Zapisz dane albumu</button>
    </form>
</div>
{% endblock %}

templates/contest/panel/album/index.html
{% extends 'panel.html' %}
​
{% block title %}Lista albumów{% endblock %}
​
{% block content %}
    <div class="jumbotron py-2 px-4">
        <h1 class="display-4">Lista albumów</h1>
        <p class="lead">Poniżej znajduje się lista albumów dostępnych w aplikacji konkursowej.</p>
        <hr class="my-4">
        <p>
            <span class="d-block mb-2">Aby dodać nowy album kliknij w przycisk poniżej:</span>
{#  sprawdza uprawnienia "perm" i wzależności od uprawnień aktywuje lub dzezaktywuje przycisk   #}
            {% if perms.contest.add_album %}
                <a class="btn btn-success" href="{% url 'panel:albums:create' %}" role="button">Dodaj album</a>
            {% else %}
                <a href="#" class="btn btn-success disabled">Dodaj album</a>
            {% endif %}
        </p>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover">
            <colgroup>
                <col span="1">
                <col span="1">
                <col span="1">
                <col span="1">
                <col span="1" style="width: 15%;">
            </colgroup>
            <thead class="thead-dark">
            <tr>
                <th>Nazwa albumu</th>
                <th>Nazwa zespołu</th>
                <th>Akcje</th>
            </tr>
            </thead>
            <tbody>
            {% for album in object_list %}
                <tr>
                    <td>{{ album.album_name }}</td>
                    <td>{{ album.author }}</td>
                    <td>
                        <div class="btn-group">
                            <a href="{% url 'panel:albums:songs-index' album_id=album.id %}" class="btn btn-dark btn-sm">Pokaż utwory</a>
                            {% if perms.contest.change_album %}
                            <a href="{% url 'panel:albums:edit' pk=album.id %}" class="btn btn-info btn-sm">Edytuj</a>
                            {% endif %}
​
                            {% if perms.contest.delete_album and perms.contest.change_album %}
                            <a href="{% url 'panel:albums:delete' pk=album.id %}" class="btn btn-danger btn-sm">Usuń</a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}