core/urls.py
from django.contrib import admin
from django.urls import path, include
from contest.views.standard_views import (
    CommonIndexView,
    PanelIndexView,
    AuthorIndexView,
    AuthorUpdateView,
    AuthorDeleteView,
    AuthorCreateView,
    SongIndexView,
    SongCreateView,
    SongUpdateView,
    SongDeleteView,
    LoginView,
    logout_view,
    VoteView,
    ContestSubmissionView
)

from contest.views.generic_views import (
    AlbumIndexView,
    AlbumCreateView,
    AlbumUpdateView,
    AlbumDeleteView
)
# te adresy URL są zrobione za pomocą
album_patterns = ([
    # http://127.0.0.1:8000/panel/albums/
    path('', AlbumIndexView.as_view(), name='index'),
    path('create/', AlbumCreateView.as_view(), name='create'),
    path('<int:pk>/edit/', AlbumUpdateView.as_view(), name="edit"),
    path('<int:pk>/delete/', AlbumDeleteView.as_view(), name="delete"),

    # http://127.0.0.1:8000/panel/albums/album_id/songs/
    path('<int:album_id>/songs/', SongIndexView.as_view(), name='songs-index'),

    path('<int:album_id>/songs/create', SongCreateView.as_view(), name='songs-create'),
    # http://127.0.0.1:8000/panel/albums/album_id/songs/song_id/edit

    path('<int:album_id>/songs/<int:song_id>/edit', SongUpdateView.as_view(), name='songs-edit'),

    path('<int:album_id>/songs/<int:song_id>/delete', SongDeleteView.as_view(), name='songs-delete'),
], 'albums')

author_patterns = ([

    path('', AuthorIndexView.as_view(), name='index'),
    path('create/', AuthorCreateView.as_view(), name='create'),
    path('<int:id>/edit/', AuthorUpdateView.as_view(), name='update'),
    path('<int:id>/delete/', AuthorDeleteView.as_view(), name='delete'),
], 'authors')

panel_patterns = ([
    # główna strona dla ZALOGOWANYCH, url: http://127.0.0.1:8000/panel/
    path('', PanelIndexView.as_view(), name='index'),

    # http://127.0.0.1:8000/panel/authors/
    path('authors/', include(author_patterns)),  # zawiera ścieżki z author_patterns

    #  http://127.0.0.1:8000/panel/albums/
    path('albums/', include(album_patterns)),  # zawiera ścieżki z album_patterns
], 'panel')

urlpatterns = [
    path('admin/', admin.site.urls),

    # główna strona palikacji dla nie zalogowanych, url: http://127.0.0.1:8000
    path('', CommonIndexView.as_view(), name='common-index'),

    # główna strona dla ZALOGOWANYCH, url: http://127.0.0.1:8000/panel/
    path('panel/', include(panel_patterns)),  # zawiera ścieżki z panel_patterns

    #
    path('login/', LoginView.as_view(), name='login'),

    #
    path('logout/', logout_view, name='logout'),

    # głosowanie na piosenki, widok bez szablonu html
    path('vote/', VoteView.as_view(), name='vote'),

    # zliczanie głosów, widok bez szablonu html
    path('submission/', ContestSubmissionView.as_view(), name='submission')
]

contest/models.py
from django.core.exceptions import ValidationError
from django.db import models
from datetime import datetime


class Author(models.Model):
    first_name = models.CharField(max_length=64, null=True)
    last_name = models.CharField(max_length=64, null=True)
    birth_date = models.DateField(null=True)
    band_name = models.CharField(max_length=255)
    debut = models.DateField(null=True, verbose_name="rok debiutu")

    @property
    def name(self):
        if (self.first_name is not None) and (self.last_name is not None):
            return "{} {}".format(self.first_name, self.last_name)
        return self.band_name

    def __str__(self):
        return self.band_name

class Album(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name="Nazwa zespołu", related_name="author")
    album_name = models.CharField(max_length=100, verbose_name="Nazwa albumu")
    # poniżej ustawiamy jakie informacje będzie zwracać klasa
    # ponieważ "author" ma klucz obcy do Author to "Album" może zwracać dane z klasy Author
    def __str__(self):
        return f"{self.album_name} ({self.author.band_name})"


class Song(models.Model):
    song_name = models.CharField(max_length=64)
    year = models.IntegerField(verbose_name="Rok powstania piosenki")
    album = models.ForeignKey(Album, on_delete=models.CASCADE, related_name="album")
    yt_link = models.CharField(max_length=255, null=True, )
    sort_order = models.IntegerField(default=0)

    # walidator dla pola "year" i "yt_link"
    def clean(self):
        if int(self.year) < 1900 or int(self.year) > datetime.now().year:
            raise ValidationError('Year is not valid, it should be between 1900 - curren year')
        if self.yt_link != '#' and not self.yt_link.startswith('https://www.youtube.com'):
            raise ValidationError('Wrong youtube link!')

    def __str__(self):
        return "{} ({})".format(self.song_name, self.album.album_name)


class SongVotes(models.Model):
    song = models.ForeignKey(Song, on_delete=models.CASCADE, related_name="songVotes")
    vote_hash = models.TextField()

    def __str__(self):
        return self.vote_hash


class ContestSubmission(models.Model):
    song = models.ForeignKey(Song, on_delete=models.CASCADE, related_name="songSubmission")
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    telephone = models.CharField(max_length=15)
    email = models.CharField(max_length=64)
    context = models.TextField()

    def __str__(self):
        return "{} {} ({})".format(self.first_name, self.last_name, self.song.song_name)

templates/contest/panel/author/create.html
{% extends 'panel.html' %}
​​{% load crispy_forms_tags %}
{% load static %}

{% block extra_stylesheets %}
<link rel="stylesheet" href="{% static 'css/datepicker.min.css' %}">
{% endblock %}

{% block extra_javascript %}
<script src="{% static 'js/datepicker.min.js' %}"></script>
<script>
    $('#id_birth_date,#id_debut').datepicker({
        format:'dd/mm/yyyy',
        autoHide: true
    });
</script>
{% endblock %}

{% block title %}Dodaj autora{% endblock %}
​
{% block content %}
    <div class="jumbotron py-2 px-4">
        <h1 class="display-4">Dodaj autora</h1>
        <hr class="my-4">
        <a class="btn btn-info" href="{%  url 'panel:authors:index' %}" role="button">Wróć do spisu</a>
    </div>
    <div>
        <form method="post" action="{% url 'panel:authors:create' %}" class="form">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Zapisz dane</button>
        </form>
    </div>
{% endblock %}

templates/contest/panel/author/edit.html
{% extends 'panel.html' %}
​​{% load crispy_forms_tags %}
{% load static %}

{% block extra_stylesheets %}
<link rel="stylesheet" href="{% static 'css/datepicker.min.css' %}">
{% endblock %}

{% block extra_javascript %}
<script src="{% static 'js/datepicker.min.js' %}"></script>
<script>
    $('#id_birth_date,#id_debut').datepicker({
        format:'dd/mm/yyyy',
        autoHide: true
    });
</script>
{% endblock %}

{% block title %}Edycja autora: {{ author.first_name }} {{ author.last_name }}{% endblock %}
​
{% block content %}
    <div class="jumbotron py-2 px-4">
        <h1 class="display-4">Edytuj autora</h1>
        <hr class="my-4">
        <a class="btn btn-info" href="{%  url 'panel:authors:index' %}" role="button">Wróć do spisu</a>
    </div>
    <div>
        <form method="post" action="{% url 'panel:authors:update' id=author.id %}" class="form">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Edytuj dane Autora</button>
        </form>
    </div>
{% endblock %}

templates/contest/panel/author/index.html
{% extends 'panel.html' %}
​
{% block title %}Lista autorów{% endblock %}
​
{% block content %}
    <div class="jumbotron py-2 px-4">
        <h1 class="display-4">Spis autorów</h1>
        <p class="lead">Poniżej znajduje się lista autorów dostępnych w aplikacji konkursowej.</p>
        <hr class="my-4">
        <p>
            <span class="d-block mb-2">Aby dodać nowego autora kliknij w przycisk poniżej:</span>
            <a class="btn btn-success" href="{% url 'panel:authors:create' %}" role="button">Dodaj autora</a>
        </p>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover">
            <colgroup>
                <col span="1">
                <col span="1">
                <col span="1">
                <col span="1">
                <col span="1" style="width: 15%;">
            </colgroup>
            <thead class="thead-dark">
            <tr>
                <th>Nazwa zespołu</th>
                <th>Imię</th>
                <th>Nazwisko</th>
                <th>Data założenia</th>
                <th>Akcje</th>
            </tr>
            </thead>
            <tbody>
            {% for author in authors %}
                <tr>
                    <td>{{ author.band_name }}</td>
                    <td>
                        {% if author.first_name %}
                            {{ author.first_name }}
                        {% else %}
                            Brak
                        {% endif %}
                    </td>
                    <td>
                        {% if author.last_name %}
                            {{ author.last_name }}
                        {% else %}
                            Brak
                        {% endif %}
                    </td>
                    <td>
                        {% if author.debut %}
                            {{ author.debut|date:"Y" }}
                        {% else %}
                            Nie podano
                        {% endif %}
                    </td>
                    <td>
                        <div class="btn-group">
                            <a href="{% url 'panel:authors:update' id=author.id %}" class="btn btn-info btn-sm">Edytuj</a>
                            <a href="{% url 'panel:authors:delete' id=author.id %}" class="btn btn-danger btn-sm">Usuń</a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}